// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module NPC(
  input        clock,
               reset,
  output [7:0] io_pc,
  input  [7:0] io_inst,
               io_btn,
               io_sw,
  output [7:0] io_led,
  output       io_led_valid,
  output [7:0] io_seg8,
  output       io_seg8_valid
);

  reg  [7:0] _GEN;
  reg  [7:0] _GEN_0;
  reg  [7:0] _GEN_1;
  reg  [7:0] _GEN_2;
  reg  [7:0] _GEN_3;
  wire       _GEN_4 = io_inst[7:6] == 2'h1;
  wire       _GEN_5 = _GEN_4 & io_inst[3];
  reg  [7:0] casez_tmp;
  always_comb begin
    casez ((&(io_inst[7:6])) ? 2'h0 : io_inst[3:2])
      2'b00:
        casez_tmp = _GEN;
      2'b01:
        casez_tmp = _GEN_0;
      2'b10:
        casez_tmp = _GEN_1;
      default:
        casez_tmp = _GEN_2;
    endcase
  end // always_comb
  reg  [7:0] casez_tmp_0;
  always_comb begin
    casez (_GEN_5 ? io_inst[5:4] : io_inst[1:0])
      2'b00:
        casez_tmp_0 = _GEN;
      2'b01:
        casez_tmp_0 = _GEN_0;
      2'b10:
        casez_tmp_0 = _GEN_1;
      default:
        casez_tmp_0 = _GEN_2;
    endcase
  end // always_comb
  wire       _GEN_6 = io_inst[2:0] == 3'h0;
  wire       _GEN_7 = io_inst[2:0] == 3'h1;
  wire       _GEN_8 = io_inst[7:6] == 2'h0;
  wire       _GEN_9 = _GEN_4 & ~(io_inst[3]);
  wire       _GEN_10 = io_inst[7:6] == 2'h2;
  wire [8:0] _GEN_11 = {7'h0, io_inst[1:0]} << {6'h0, io_inst[3:2], 1'h0};
  wire [7:0] _GEN_12 =
    (_GEN_8 ? casez_tmp + casez_tmp_0 : 8'h0) | (_GEN_10 ? _GEN_11[7:0] : 8'h0)
    | (_GEN_9 ? (_GEN_6 ? io_sw : 8'h0) | (_GEN_7 ? io_btn : 8'h0) : 8'h0);
  wire       _GEN_13 = _GEN_8 | _GEN_10 | _GEN_9;
  always @(posedge clock) begin
    if (_GEN_13 & io_inst[5:4] == 2'h0)
      _GEN <= _GEN_12;
    if (_GEN_13 & io_inst[5:4] == 2'h1)
      _GEN_0 <= _GEN_12;
    if (_GEN_13 & io_inst[5:4] == 2'h2)
      _GEN_1 <= _GEN_12;
    if (_GEN_13 & (&(io_inst[5:4])))
      _GEN_2 <= _GEN_12;
    if (reset)
      _GEN_3 <= 8'h0;
    else
      _GEN_3 <=
        _GEN_3
        + (casez_tmp != casez_tmp_0 & (&(io_inst[7:6]))
             ? {{4{io_inst[5]}}, io_inst[5:2]}
             : 8'h1);
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        _GEN = _RANDOM[1'h0][7:0];
        _GEN_0 = _RANDOM[1'h0][15:8];
        _GEN_1 = _RANDOM[1'h0][23:16];
        _GEN_2 = _RANDOM[1'h0][31:24];
        _GEN_3 = _RANDOM[1'h1][7:0];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_pc = _GEN_3;
  assign io_led = casez_tmp_0;
  assign io_led_valid = _GEN_5 & _GEN_6;
  assign io_seg8 = casez_tmp_0;
  assign io_seg8_valid = _GEN_5 & _GEN_7;
endmodule

